[package]
name = "mchp_gpio_ctl"
version = "0.1.3"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
#nusb = "0.1"
nusb = "0.2.0-beta"

[patch.crates-io]
nusb = { git = "https://github.com/kevinmehall/nusb.git" } # need port_chain