[package]
name = "mchp_gpio_ctl"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
nusb = "0.2.0"
bitfield-struct = "0.11"
# paste = "1"
colored = "3"